use super::ReferenceComparison;

/// Returns static reference comparison data across all domains.
/// These are published/estimated performance ratios, not live measurements.
pub fn reference_comparisons() -> Vec<ReferenceComparison> {
    let r = |domain: &str, cat: &str, lib: &str, factor: f64, notes: &str| ReferenceComparison {
        domain: domain.into(),
        category: cat.into(),
        library: lib.into(),
        factor,
        notes: notes.into(),
    };
    vec![
        // ── Compute: Parallel map / transform ────────────────────────
        r(
            "Compute",
            "Parallel Map",
            "rayon par_iter (Rust)",
            0.95,
            "Same backend; ~5% dispatch overhead",
        ),
        r(
            "Compute",
            "Parallel Map",
            "std::iter (Rust, sequential)",
            0.15,
            "Single-threaded baseline",
        ),
        r(
            "Compute",
            "Parallel Map",
            "NumPy vectorized (Python)",
            0.6,
            "C inner loop but Python dispatch + GIL",
        ),
        r(
            "Compute",
            "Parallel Map",
            "Bun (JS, JIT-compiled)",
            0.08,
            "V8-level JIT; no SIMD auto-vectorization",
        ),
        r(
            "Compute",
            "Parallel Map",
            "Node.js worker_threads",
            0.05,
            "JS overhead + serialization between workers",
        ),
        r(
            "Compute",
            "Parallel Map",
            "Deno (V8 + Rust internals)",
            0.07,
            "Similar to Bun/Node; slight Rust FFI edge",
        ),
        // ── Compute: Sort ────────────────────────────────────────────
        r(
            "Compute",
            "Sort",
            "rayon par_sort_unstable (Rust)",
            1.0,
            "Same implementation",
        ),
        r(
            "Compute",
            "Sort",
            "std::sort_unstable (Rust)",
            0.25,
            "Single-threaded pdqsort",
        ),
        r(
            "Compute",
            "Sort",
            "polars sort (Rust/Arrow)",
            0.85,
            "Arrow columnar + rayon",
        ),
        r(
            "Compute",
            "Sort",
            "pandas sort_values (Python)",
            0.3,
            "NumPy/timsort; single-threaded by default",
        ),
        r(
            "Compute",
            "Sort",
            "Bun Array.sort (JS)",
            0.12,
            "V8 TimSort; no parallelism",
        ),
        // ── Compute: GEMM / Matrix Multiply ──────────────────────────
        r(
            "Compute",
            "GEMM",
            "OpenBLAS dgemm",
            15.0,
            "Hand-tuned BLAS with SIMD kernels",
        ),
        r(
            "Compute",
            "GEMM",
            "Intel MKL dgemm",
            20.0,
            "Intel-optimized; --features mkl",
        ),
        r(
            "Compute",
            "GEMM",
            "cuBLAS (NVIDIA GPU)",
            100.0,
            "GPU tensor cores; --features cuda",
        ),
        r(
            "Compute",
            "GEMM",
            "PyTorch matmul (CPU)",
            12.0,
            "Uses OpenBLAS/MKL internally",
        ),
        r(
            "Compute",
            "GEMM",
            "PyTorch matmul (CUDA)",
            120.0,
            "cuBLAS + tensor cores",
        ),
        r(
            "Compute",
            "GEMM",
            "TensorFlow matmul (CPU)",
            11.0,
            "Eigen/MKL backend",
        ),
        r(
            "Compute",
            "GEMM",
            "NumPy dot (Python)",
            10.0,
            "BLAS backend (OpenBLAS/MKL)",
        ),
        // ── Compute: Reduction ───────────────────────────────────────
        r(
            "Compute",
            "Reduction",
            "rayon par_iter().sum()",
            1.0,
            "Same implementation",
        ),
        r(
            "Compute",
            "Reduction",
            "numpy.sum() (Python)",
            0.7,
            "C inner loop; Python overhead",
        ),
        r(
            "Compute",
            "Reduction",
            "PyTorch .sum() CPU",
            0.8,
            "Optimized AVX reduction",
        ),
        r(
            "Compute",
            "Reduction",
            "polars sum (Rust/Arrow)",
            0.9,
            "Arrow + SIMD",
        ),
        r(
            "Compute",
            "Reduction",
            "Bun reduce (JS)",
            0.06,
            "V8 JIT; no SIMD",
        ),
        // ── UI: Render list assembly ─────────────────────────────────
        r(
            "UI Rendering",
            "Render List",
            "React (virtual DOM reconciliation)",
            0.005,
            "JS VDOM diff + fiber scheduler; ~200x slower",
        ),
        r(
            "UI Rendering",
            "Render List",
            "Angular (Renderer2 + change detection)",
            0.004,
            "Zone.js + incremental DOM",
        ),
        r(
            "UI Rendering",
            "Render List",
            "Vue 3 (Proxy reactivity + patch)",
            0.006,
            "Faster VDOM than React; still JS overhead",
        ),
        r(
            "UI Rendering",
            "Render List",
            "Svelte (compiled output, no VDOM)",
            0.015,
            "Compiled; less overhead than React/Vue",
        ),
        r(
            "UI Rendering",
            "Render List",
            "Solid.js (fine-grained reactivity)",
            0.02,
            "No VDOM; signals-based; still JS",
        ),
        r(
            "UI Rendering",
            "Render List",
            "Vanilla JS (document.createElement)",
            0.01,
            "No framework; JS→C++ bridge per call",
        ),
        r(
            "UI Rendering",
            "Render List",
            "Dioxus (Rust VDOM)",
            0.3,
            "Rust VDOM diffing; same language",
        ),
        r(
            "UI Rendering",
            "Render List",
            "Yew (Rust VDOM + WASM)",
            0.25,
            "WASM + VDOM; WebAssembly overhead",
        ),
        r(
            "UI Rendering",
            "Render List",
            "egui (Rust immediate mode)",
            0.5,
            "No VDOM; immediate mode; retained allocs",
        ),
        r(
            "UI Rendering",
            "Render List",
            "iced (Rust Elm arch)",
            0.4,
            "Elm architecture; message passing overhead",
        ),
        // ── UI: Animation / transitions ──────────────────────────────
        r(
            "Animation",
            "Transition Tick",
            "React Spring (JS)",
            0.02,
            "Physics-based; per-frame allocations + GC",
        ),
        r(
            "Animation",
            "Transition Tick",
            "GSAP (JS)",
            0.03,
            "Optimized JS tweening; still GC-bound for batches",
        ),
        r(
            "Animation",
            "Transition Tick",
            "Framer Motion (React)",
            0.015,
            "React + spring physics; component overhead",
        ),
        r(
            "Animation",
            "Transition Tick",
            "Angular Animations",
            0.015,
            "AnimationBuilder + Zone.js scheduling",
        ),
        r(
            "Animation",
            "Transition Tick",
            "CSS Transitions (browser-native)",
            0.1,
            "Compositor-accelerated; limited to style props",
        ),
        r(
            "Animation",
            "Transition Tick",
            "Web Animations API (JS)",
            0.05,
            "Browser-native; JS bridge overhead",
        ),
        r(
            "Animation",
            "Transition Tick",
            "Bevy Transform animation (Rust/ECS)",
            0.7,
            "ECS batch iteration; no GC",
        ),
        r(
            "Animation",
            "Transition Tick",
            "Unity Animator (C#)",
            0.3,
            "C# managed heap; state machine overhead",
        ),
        r(
            "Animation",
            "Transition Tick",
            "Godot Tween (GDScript)",
            0.1,
            "Interpreted GDScript; node tree traversal",
        ),
        // ── UI: Data virtualization ──────────────────────────────────
        r(
            "UI Rendering",
            "Data Virtualization",
            "react-window (JS)",
            0.01,
            "JS row measurement + React reconciliation",
        ),
        r(
            "UI Rendering",
            "Data Virtualization",
            "react-virtuoso (JS)",
            0.008,
            "Dynamic height measurement; heavier than react-window",
        ),
        r(
            "UI Rendering",
            "Data Virtualization",
            "AG Grid (JS)",
            0.005,
            "Enterprise grid; feature-heavy DOM management",
        ),
        r(
            "UI Rendering",
            "Data Virtualization",
            "Tabulator (JS)",
            0.007,
            "Vanilla JS grid; no framework dep",
        ),
        // ── Interpolation ────────────────────────────────────────────
        r(
            "Math",
            "Lerp / Interpolation",
            "JS Math (manual lerp)",
            0.08,
            "V8 JIT; boxed doubles, no SIMD auto-vec",
        ),
        r(
            "Math",
            "Lerp / Interpolation",
            "glMatrix (JS)",
            0.1,
            "TypedArrays; no SIMD without WASM",
        ),
        r(
            "Math",
            "Lerp / Interpolation",
            "Unity Mathf.Lerp (C#)",
            0.4,
            "JIT-compiled C#; Mono/IL2CPP",
        ),
        r(
            "Math",
            "Lerp / Interpolation",
            "Godot lerp (GDScript)",
            0.05,
            "Interpreted; per-call overhead",
        ),
        r(
            "Math",
            "Lerp / Interpolation",
            "Bevy Vec3::lerp (Rust)",
            0.95,
            "Same language; glam SIMD",
        ),
        r(
            "Math",
            "Lerp / Interpolation",
            "NumPy interp (Python)",
            0.3,
            "Vectorized C; Python dispatch",
        ),
        // ── Game engines: frame time / ECS ───────────────────────────
        r(
            "Game Engine",
            "ECS Iteration (10K entities)",
            "Bevy ECS (Rust)",
            0.9,
            "Archetype storage; cache-friendly",
        ),
        r(
            "Game Engine",
            "ECS Iteration (10K entities)",
            "Unity DOTS/ECS (C#)",
            0.6,
            "Burst compiler; managed GC pauses",
        ),
        r(
            "Game Engine",
            "ECS Iteration (10K entities)",
            "Godot (GDScript)",
            0.05,
            "Scene tree; interpreted; no ECS",
        ),
        r(
            "Game Engine",
            "ECS Iteration (10K entities)",
            "Unreal Engine (C++)",
            0.7,
            "UObject system; GC + reflection",
        ),
        r(
            "Game Engine",
            "Frame Update Loop",
            "Bevy (Rust)",
            0.85,
            "Pure ECS; zero GC",
        ),
        r(
            "Game Engine",
            "Frame Update Loop",
            "Unity (C# Mono)",
            0.3,
            "GC pauses; managed overhead",
        ),
        r(
            "Game Engine",
            "Frame Update Loop",
            "Godot 4.x (GDScript)",
            0.1,
            "Interpreted scripts; node tree",
        ),
        r(
            "Game Engine",
            "Frame Update Loop",
            "Unreal Engine 5 (C++)",
            0.5,
            "Nanite/Lumen overhead; heavy runtime",
        ),
        // ── AI / ML inference latency ────────────────────────────────
        r(
            "AI Inference",
            "Elementwise (10M f64)",
            "PyTorch CPU",
            0.8,
            "ATen C++ core; operator dispatch overhead",
        ),
        r(
            "AI Inference",
            "Elementwise (10M f64)",
            "TensorFlow CPU",
            0.7,
            "Eigen backend; graph execution overhead",
        ),
        r(
            "AI Inference",
            "Elementwise (10M f64)",
            "ONNX Runtime CPU",
            0.85,
            "Optimized graph; less overhead than TF",
        ),
        r(
            "AI Inference",
            "Elementwise (10M f64)",
            "JAX CPU",
            0.75,
            "XLA compilation; great for large batches",
        ),
        r(
            "AI Inference",
            "Batch Matmul Latency",
            "PyTorch CUDA",
            150.0,
            "cuBLAS + tensor cores; GPU memory BW",
        ),
        r(
            "AI Inference",
            "Batch Matmul Latency",
            "TensorRT (NVIDIA)",
            200.0,
            "Fused kernels; INT8/FP16 quantization",
        ),
        r(
            "AI Inference",
            "Batch Matmul Latency",
            "ONNX Runtime CUDA",
            130.0,
            "cuDNN backend; graph optimization",
        ),
        r(
            "AI Inference",
            "Token Generation (LLM)",
            "llama.cpp CPU (AVX2)",
            0.6,
            "Quantized INT4/INT8; hand-tuned SIMD",
        ),
        r(
            "AI Inference",
            "Token Generation (LLM)",
            "llama.cpp CUDA",
            20.0,
            "GPU inference; depends on model size",
        ),
        r(
            "AI Inference",
            "Token Generation (LLM)",
            "vLLM (Python/CUDA)",
            25.0,
            "PagedAttention; optimized KV cache",
        ),
        // ── Event handling ───────────────────────────────────────────
        r(
            "Events",
            "Event Dispatch (batch 10k)",
            "React SyntheticEvent",
            0.03,
            "Pooled event objects + React fiber scheduler; GC on large batches",
        ),
        r(
            "Events",
            "Event Dispatch (batch 10k)",
            "DOM native Event (browser)",
            0.05,
            "C++ native; JS bridge per dispatch call",
        ),
        r(
            "Events",
            "Event Dispatch (batch 10k)",
            "Vue 3 emit",
            0.04,
            "Proxy-based reactivity; lighter than React but still JS dispatch",
        ),
        r(
            "Events",
            "Event Dispatch (batch 10k)",
            "Angular EventEmitter",
            0.02,
            "Zone.js + change detection trigger; heaviest framework overhead",
        ),
        r(
            "Events",
            "Event Dispatch (batch 10k)",
            "Svelte dispatch (compiled)",
            0.08,
            "Compiled to direct DOM calls; lightest web framework",
        ),
        r(
            "Events",
            "Hit-Test (100k rects)",
            "react-use-gesture",
            0.01,
            "JS bounding rect API per pointer event + React state update",
        ),
        r(
            "Events",
            "Hit-Test (100k rects)",
            "Hammer.js",
            0.02,
            "Gesture recognizer; JS touch/pointer API overhead",
        ),
        r(
            "Events",
            "Hit-Test (100k rects)",
            "Bevy (Rust ECS hit-test)",
            0.7,
            "Archetype storage; cache-friendly AABB iteration",
        ),
        r(
            "Events",
            "3-Phase Propagation",
            "DOM capture/bubble",
            0.04,
            "Browser-native C++ propagation + JS listener invocation overhead",
        ),
        r(
            "Events",
            "3-Phase Propagation",
            "React event delegation (root)",
            0.03,
            "Single root listener + synthetic event construction",
        ),
    ]
}
